name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 4.0.4

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_android:
    git:
      url: https://github.com/sereja93/plugins-flutter.git
      path: packages/webview_flutter/webview_flutter_android
  webview_flutter_platform_interface: ^2.0.0


dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  plugin_platform_interface: ^2.1.3
